### ISSUE TITLE
Incorrect WDIO reporter tool output location

### ISSUE THREAD

**Issue by Coronad1** [cerner/terra-toolkit-boneyard#42]
# Bug Report

## Description

After pulling in the most recent version of terra-toolkit (6.4.0), we are seeing the WDIO reporter tool that was added in placing the report JSON in the incorrect location. Instead of nesting the report in the generated 'reports' folder, it generates it within the 'wdio' folder. This causes the generated report to by-pass gitignore setting for reports folders.

## Steps to Reproduce

1. Have a WDIO spec set up, with the project using terra-toolkit 6.4.0
2. Run 'npm run test:wdio'
3. See output report location

## Additional Context / Screenshots

Here is a screenshot of the file-structure output for reference (project name blocked out):
![terra-toolkit-issue](https://user-images.githubusercontent.com/68032621/86970381-e86ae080-c134-11ea-9be7-dac1401abf05.png)

## Expected Behavior

The outputted report file should have been nested within the generated reports folder as far as I am aware from reading the change docs and code change itself.

## Possible Solution

I assume it has to do with the pathing/generation of the report in the update to the wdio configuration file that was made in one of the recent 6.x.0 releases.

## Environment

* Component Name and Version: terra-toolkit, 6.4.0
* Browser Name and Version: N/A
* Node/npm Version: [e.g. Node 8/npm 5] Node 10.16.0 / npm 6.9.0
* Webpack Version: 4.43.0 (^4.30.0 in package.json)
* Operating System and version (desktop or mobile): Desktop, Ubuntu 18.04.4 run through a virtualbox VM

## @ Mentions

I was told to log this issue by @emilyrohrbough

**Comment by emilyrohrbough** [comment]
https://github.com/cerner/terra-toolkit-boneyard/blob/main/reporters/wdio/TerraWDIOSpecReporter.js#L142

this line should be 
```diff
- if (index === 1) {
+ if (index === 0) {
```

If only one spec file is ran during the wdio run, the file name results in:
```
./tests/wdio/reports-packageName.json
```
instead of 
```
./tests/wdio/reports/report-locale-packageName.json
```
because `this.fileName = ''`
