### ISSUE TITLE
Support of node 12

### ISSUE THREAD

**Issue by VladFernoaga** [cerner/terra-toolkit-boneyard#76]
# Feature Request

## Description
It would be great that terra-toolkit to support Node 12 and above as currently in our project this is the only dependency that limits us from using Node 12. 

## Additional Context / Screenshots
Considering that node 10 will go out of maintenance mid April 2021, I see this as a pretty highly important feature.  
https://nodejs.org/en/about/releases/

Are there any plans in this direction?

**Comment by emilyrohrbough** [comment]
Hey @VladFernoaga, `terra-toolkit` is current being restructured to a mono-repo in the https://github.com/cerner/terra-toolkit. With this restructure, we are introducing the `tera-functional-testing` package which will provide wdio test dependencies. This package will be up lifted to use wdio v6 (toolkit-boneyard is on v4) which will support Node 12. You can follow along on this issue if you'd like: https://github.com/cerner/terra-toolkit/issues/401.

**Comment by ryanthemanuel** [comment]
Closing this in lieu of https://github.com/cerner/terra-toolkit/issues/401
