### ISSUE TITLE
Incorrect updateReference option propagation to clean screenshots.

### ISSUE THREAD

**Issue by hegedusm** [cerner/terra-toolkit-boneyard#82]
# Bug Report

## Description
wdio-runner-cli incorrectly pass **updateReference** as an option to clean snapshots. Clean snapshots function expects **removeReference** as an option.

## Steps to Reproduce
Execute wdio-runner-cli, set parameter updateReference to true. The description says 'Pass to remove all reference screenshots during screenshot cleanup'. Reference screenshots are not removed.

## Additional Context / Screenshots
N/A

## Expected Behavior
References removed according to updateReference option.

## Possible Solution
Pass updateReference as removeReference. 
cleanScreenshots({
  removeReference: updateReference,
});

**Comment by ryanthemanuel** [comment]
Hi @hegedusm. We have recently made the cleaning of snapshots a lot easier with our new terra-functional-testing package. I would strongly recommend upgrading when you have the time as we have improved a lot of things as well. With the new package, terra-toolkit-boneyard is in maintenance mode and will only be modified to fix major issues, so I'm going to go ahead and close this.
